// Portions of this file are derived from getsentry/sentry-dart
// Copyright (c) 2020 Sentry
// Licensed under the MIT License: https://github.com/getsentry/sentry-dart/blob/main/LICENSE

import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:posthog_flutter/src/util/logging.dart';
import 'package:stack_trace/stack_trace.dart';
import 'utils/isolate_utils.dart' as isolate_utils;
import 'posthog_exception.dart';
import 'origin.dart';
import 'chunk_ids.dart';

typedef ChunkIdMapType = Map<String, String>;

class DartExceptionProcessor {
  /// Maximum number of exception items in `$exception_list` when walking an
  /// error's cause chain (outermost error plus its causes).
  static const maxExceptionChainLength = 50;

  /// Converts Dart error/exception and stack trace to PostHog exception format
  static Map<String, dynamic> processException({
    required Object error,
    StackTrace? stackTrace,
    Map<String, Object>? properties,
    List<String>? inAppIncludes,
    List<String>? inAppExcludes,
    bool inAppByDefault = true,
    StackTrace Function()? stackTraceProvider, //for testing
  }) {
    // Extract PostHog metadata if error is wrapped in PostHogException
    var mechanismType = 'generic';
    var handled = true;
    var level = 'error';
    String? captureSource;
    var currentError = error;

    if (error is PostHogException) {
      handled = error.handled;
      mechanismType = error.mechanism;
      level = _normalizeLevel(error.level) ?? 'error';
      captureSource = error.captureSource;
      currentError = error.source;
    }

    StackTrace? effectiveStackTrace = stackTrace;
    bool isGeneratedStackTrace = false;

    // If it's an Error, try to use its built-in stackTrace
    if (currentError is Error) {
      effectiveStackTrace ??= currentError.stackTrace;
    }

    // If still null or empty, get current stack trace
    if (effectiveStackTrace == null ||
        effectiveStackTrace == StackTrace.empty) {
      effectiveStackTrace = stackTraceProvider?.call() ?? StackTrace.current;
      isGeneratedStackTrace = true; // Flag to remove top PostHog frames
    }

    // Check if we still have an empty stack trace
    final hasValidStackTrace = effectiveStackTrace != StackTrace.empty;

    // Process primary exception
    final frames = hasValidStackTrace
        ? _parseStackTrace(
            effectiveStackTrace,
            inAppIncludes: inAppIncludes,
            inAppExcludes: inAppExcludes,
            inAppByDefault: inAppByDefault,
            removeTopPostHogFrames: isGeneratedStackTrace,
          )
        : <Map<String, dynamic>>[];

    final errorType = _getExceptionType(currentError);

    // Mark exception as synthetic if:
    // - runtimeType.toString() returned empty/null (fallback to 'Error' type)
    // - Stack trace was generated by PostHog (not from original exception)
    // - No valid stack trace is available
    final isSynthetic = !_isRuntimeException(currentError) ||
        errorType == null ||
        isGeneratedStackTrace ||
        !hasValidStackTrace;

    final exceptionData = <String, dynamic>{
      'type': errorType ?? 'Error',
      'mechanism': {
        'handled': handled,
        'synthetic': isSynthetic,
        'type': mechanismType,
        'exception_id': 0,
      },
    };

    // Add exception message, if available
    exceptionData['value'] = currentError.toString();

    // Add stacktrace, if any frames are available
    if (frames.isNotEmpty) {
      exceptionData['stacktrace'] = {'frames': frames, 'type': 'raw'};
    }

    // Add thread ID, if available
    final threadId = _getCurrentThreadId();
    if (threadId != null) {
      exceptionData['thread_id'] = threadId;
    }

    // Walk the error's cause chain into additional exception items,
    // outermost-first (wrapper first, root cause last)
    final exceptionList = <Map<String, dynamic>>[exceptionData];
    _appendCauses(
      exceptionList,
      currentError,
      parentId: 0,
      threadId: threadId,
      inAppIncludes: inAppIncludes,
      inAppExcludes: inAppExcludes,
      inAppByDefault: inAppByDefault,
    );

    final safeProperties = properties == null
        ? <String, Object>{}
        : Map<String, Object>.fromEntries(
            properties.entries.where(
              (entry) => !_reservedExceptionProperties.contains(entry.key),
            ),
          );
    final result = <String, dynamic>{
      ...safeProperties,
      '\$exception_level': level,
      '\$exception_list': exceptionList,
      if (captureSource != null) '\$exception_source': captureSource,
    };

    return result;
  }

  /// Appends one exception item per cause of [error] to [exceptionList],
  /// outermost-first, guarding against cycles and capping the chain at
  /// [maxExceptionChainLength] items.
  static void _appendCauses(
    List<Map<String, dynamic>> exceptionList,
    Object error, {
    required int parentId,
    required int? threadId,
    List<String>? inAppIncludes,
    List<String>? inAppExcludes,
    bool inAppByDefault = true,
  }) {
    final seen = Set<Object>.identity()..add(error);
    _appendCauseItems(
      exceptionList,
      _getCauses(error),
      seen,
      parentId: parentId,
      threadId: threadId,
      inAppIncludes: inAppIncludes,
      inAppExcludes: inAppExcludes,
      inAppByDefault: inAppByDefault,
    );
  }

  static void _appendCauseItems(
    List<Map<String, dynamic>> exceptionList,
    Iterable<(Object, String)> causes,
    Set<Object> seen, {
    required int parentId,
    required int? threadId,
    List<String>? inAppIncludes,
    List<String>? inAppExcludes,
    bool inAppByDefault = true,
  }) {
    for (final (cause, relationship) in causes) {
      if (exceptionList.length >= maxExceptionChainLength || !seen.add(cause)) {
        continue;
      }

      final causeType = _getExceptionType(cause);
      final causeData = <String, dynamic>{
        'type': causeType ?? 'Error',
        'mechanism': {
          'synthetic': !_isRuntimeException(cause),
          'type': 'chained',
          'source': relationship,
          'exception_id': exceptionList.length,
          'parent_id': parentId,
        },
        'value': cause.toString(),
      };

      // Only use the cause's own stack trace; never generate one for causes
      final causeStackTrace = _extractOwnStackTrace(cause);
      if (causeStackTrace != null) {
        final frames = _parseStackTrace(
          causeStackTrace,
          inAppIncludes: inAppIncludes,
          inAppExcludes: inAppExcludes,
          inAppByDefault: inAppByDefault,
        );
        if (frames.isNotEmpty) {
          causeData['stacktrace'] = {'frames': frames, 'type': 'raw'};
        }
      }

      if (threadId != null) {
        causeData['thread_id'] = threadId;
      }

      final causeId = exceptionList.length;
      exceptionList.add(causeData);
      _appendCauseItems(
        exceptionList,
        _getCauses(cause),
        seen,
        parentId: causeId,
        threadId: threadId,
        inAppIncludes: inAppIncludes,
        inAppExcludes: inAppExcludes,
        inAppByDefault: inAppByDefault,
      );
    }
  }

  /// Extracts the causes of an error, if the error type exposes any.
  ///
  /// Supports [AsyncError] (unwraps to the original error),
  /// [ParallelWaitError] (walks all non-null errors) and the common duck-typed
  /// `cause` getter convention used by custom exceptions.
  static Iterable<(Object, String)> _getCauses(Object error) sync* {
    if (error is AsyncError) {
      yield (error.error, 'unwrap');
      return;
    }

    if (error is ParallelWaitError) {
      for (final member in _parallelErrors(error.errors)) {
        yield (member, 'member');
      }
      return;
    }

    try {
      // ignore: avoid_dynamic_calls
      final cause = (error as dynamic).cause;
      if (cause is Object && !identical(cause, error)) {
        yield (cause, 'cause');
      }
    } catch (_) {
      // Error type doesn't expose a `cause` getter
    }
  }

  static const _reservedExceptionProperties = {
    '\$exception_list',
    '\$exception_level',
    '\$exception_source',
    '\$debug_images',
    '\$exception_handled',
    '\$exception_types',
    '\$exception_values',
    '\$exception_sources',
    '\$exception_functions',
    '\$exception_fingerprint_version',
    '\$exception_fingerprint_record',
    '\$exception_issue_id',
    '\$exception_release',
    '\$cymbal_errors',
  };

  static String? _normalizeLevel(String level) {
    switch (level.toLowerCase()) {
      case 'fatal':
      case 'critical':
      case 'alert':
      case 'emergency':
        return 'fatal';
      case 'error':
      case 'log':
        return level.toLowerCase();
      case 'warning':
      case 'warn':
        return 'warning';
      case 'notice':
      case 'info':
        return 'info';
      case 'trace':
      case 'debug':
        return 'debug';
      default:
        return null;
    }
  }

  static bool _isRuntimeException(Object error) =>
      error is Exception ||
      error is Error ||
      error is AsyncError ||
      error is ParallelWaitError;

  /// Returns all non-null errors from a [ParallelWaitError.errors] collection,
  /// if it is enumerable (e.g. `List<Future>.wait` produces a
  /// `List<AsyncError?>`; record-based `wait` produces a record, skipped here)
  static Iterable<Object> _parallelErrors(Object? errors) sync* {
    if (errors is Iterable) {
      for (final error in errors) {
        if (error != null) {
          yield error as Object;
        }
      }
    }
  }

  /// Returns the error's own stack trace, if it carries a usable one
  static StackTrace? _extractOwnStackTrace(Object error) {
    StackTrace? stackTrace;
    if (error is AsyncError) {
      stackTrace = error.stackTrace;
    } else if (error is Error) {
      stackTrace = error.stackTrace;
    }

    if (stackTrace == null || stackTrace == StackTrace.empty) {
      return null;
    }
    return stackTrace;
  }

  /// Determines if a stack frame belongs to PostHog SDK (just check package for now)
  static bool _isPostHogFrame(Frame frame) {
    return frame.package == 'posthog_flutter';
  }

  /// Asynchronous gap frame for separating async traces
  static const _asynchronousGapFrame = <String, dynamic>{
    'platform': 'dart',
    'abs_path': '<asynchronous suspension>',
    'in_app': false,
    'synthetic': true,
  };

  /// Parses stack trace into PostHog format
  ///
  /// Approach inspired by Sentry's stack trace factory implementation:
  /// https://github.com/getsentry/sentry-dart/blob/a69a51fd1695dd93024be80a50ad05dd990b2b82/packages/dart/lib/src/sentry_stack_trace_factory.dart#L29-L53
  static List<Map<String, dynamic>> _parseStackTrace(
    StackTrace stackTrace, {
    List<String>? inAppIncludes,
    List<String>? inAppExcludes,
    bool inAppByDefault = true,
    bool removeTopPostHogFrames = false,
  }) {
    final chain = Chain.forTrace(stackTrace);
    final frames = <Map<String, dynamic>>[];
    final chunkIdMap = getPosthogChunkIds() ?? {};

    for (final (index, trace) in chain.traces.indexed) {
      bool skipNextPostHogFrame = removeTopPostHogFrames;

      for (final frame in trace.frames) {
        // Skip top PostHog frames?
        if (skipNextPostHogFrame) {
          if (_isPostHogFrame(frame)) {
            continue;
          }
          skipNextPostHogFrame = false;
        }

        final processedFrame = _convertFrameToPostHog(
          frame,
          chunkIdMap,
          inAppIncludes: inAppIncludes,
          inAppExcludes: inAppExcludes,
          inAppByDefault: inAppByDefault,
        );
        if (processedFrame != null) {
          frames.add(processedFrame);
        }
      }

      // Add asynchronous gap frame between traces (skipping last trace)
      if (index < chain.traces.length - 1) {
        frames.add(_asynchronousGapFrame);
      }
    }

    // The stack_trace package yields frames innermost-first (crash site first,
    // entry point last). PostHog's canonical wire order is bottom-up:
    // frames[0] is the outermost/entry point and the last frame is the crash
    // site. Reverse to match; this also keeps async gap frames positioned
    // correctly between their surrounding traces.
    return frames.reversed.toList();
  }

  /// Converts a Frame from stack_trace package to PostHog format
  static Map<String, dynamic>? _convertFrameToPostHog(
    Frame frame,
    Map<String, String> chunkIdMap, {
    List<String>? inAppIncludes,
    List<String>? inAppExcludes,
    bool inAppByDefault = true,
  }) {
    final absPath = '$eventOrigin${_extractAbsolutePath(frame)}';
    final frameData = <String, dynamic>{
      'platform': kIsWeb ? 'web:javascript' : 'dart',
      'abs_path': absPath,
      'in_app': _isInAppFrame(
        frame,
        inAppIncludes: inAppIncludes,
        inAppExcludes: inAppExcludes,
        inAppByDefault: inAppByDefault,
      ),
    };

    // add package, if available
    final package = _extractPackage(frame);
    if (package != null && package.isNotEmpty) {
      frameData['package'] = package;
    }

    // add function, if available
    final member = frame.member;
    if (member != null && member.isNotEmpty) {
      frameData['function'] = member;
    }

    // Add filename, if available
    final fileName = _extractFileName(frame);
    if (fileName != null && fileName.isNotEmpty) {
      frameData['filename'] = fileName;

      // Check if any key in chunkIdMap contains the fileName as a substring
      String? chunkId;
      for (final entry in chunkIdMap.entries) {
        if (entry.key.contains(fileName)) {
          chunkId = entry.value;
          printIfDebug('chunkId found: $chunkId for fileName: $fileName');
          break;
        }
      }
      if (chunkId != null) {
        frameData['chunk_id'] = chunkId;
      }
    }

    // Add line number, if available
    final line = frame.line;
    if (line != null && line >= 0) {
      frameData['lineno'] = line;
    }

    // Add column number, if available
    final column = frame.column;
    if (column != null && column >= 0) {
      frameData['colno'] = column;
    }

    return frameData;
  }

  /// Determines if a frame is considered in-app
  static bool _isInAppFrame(
    Frame frame, {
    List<String>? inAppIncludes,
    List<String>? inAppExcludes,
    bool inAppByDefault = true,
  }) {
    final scheme = frame.uri.scheme;

    if (scheme.isEmpty) {
      // Early bail out for unknown schemes
      return inAppByDefault;
    }

    final package = frame.package;
    if (package != null) {
      // 1. Check inAppIncludes first (highest priority)
      if (inAppIncludes != null && inAppIncludes.contains(package)) {
        return true;
      }

      // 2. Check inAppExcludes second
      if (inAppExcludes != null && inAppExcludes.contains(package)) {
        return false;
      }
    }

    // 3. Hardcoded exclusions
    if (frame.isCore) {
      // dart: packages
      return false;
    }

    if (frame.package == 'flutter') {
      // flutter package
      return false;
    }

    // 4. Default fallback
    return inAppByDefault;
  }

  static String? _extractPackage(Frame frame) {
    return frame.package;
  }

  static String? _extractFileName(Frame frame) {
    return frame.uri.pathSegments.isNotEmpty
        ? frame.uri.pathSegments.last
        : null;
  }

  static String _extractAbsolutePath(Frame frame) {
    // For privacy, only return filename for local file paths
    if (frame.uri.scheme != 'dart' &&
        frame.uri.scheme != 'package' &&
        frame.uri.pathSegments.isNotEmpty) {
      return frame.uri.pathSegments.last; // Just filename for privacy
    }

    // For dart: and package: URIs, full path is safe
    return frame.uri.toString();
  }

  /// Gets the current thread ID using isolate-based detection
  static int? _getCurrentThreadId() {
    try {
      // Check if we're in the root isolate (main thread)
      if (isolate_utils.isRootIsolate()) {
        return 'main'.hashCode;
      }

      // For other isolates, use the isolate's debug name
      final isolateName = isolate_utils.getIsolateName();
      if (isolateName != null && isolateName.isNotEmpty) {
        return isolateName.hashCode;
      }

      return null;
    } catch (e) {
      return null;
    }
  }

  static String? _getExceptionType(Object error) {
    // The string is only intended for providing information to a reader while debugging. There is no guaranteed format, the string value returned for a Type instances is entirely implementation dependent.
    final type = error.runtimeType.toString();
    return type.isNotEmpty ? type : null;
  }
}
