version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "PostHog/team-client-libraries"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"
