name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: ["bug"]
body:


  - type: input
    id: version
    attributes:
      label: Version
      description: SDK Version
      placeholder: 3.0.0 ← should look like this
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true
