name: CI
on:
  push:
    branches:
      - main
    paths:
      - "packages/posthog_flutter/**"
      - ".github/workflows/ci.yml"
      - "Makefile"
      - "ktlint-baseline.xml"
  pull_request:
    paths:
      - "packages/posthog_flutter/**"
      - ".github/workflows/ci.yml"
      - "Makefile"
      - "ktlint-baseline.xml"

# Publish using custom workflow
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: 'Set up Java'
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get
        working-directory: ./packages/posthog_flutter

      - name: SDK format check
        run: |
          make installLinters
          make checkFormatDart
          make analyzeDart
          make formatKotlin
          make formatSwift
        working-directory: ./packages/posthog_flutter

      - name: Test
        run: |
          flutter test
        working-directory: ./packages/posthog_flutter

      - name: Build iOS
        working-directory: ./packages/posthog_flutter/example
        run: flutter build ios --simulator --no-codesign

      - name: Build macOS
        working-directory: ./packages/posthog_flutter/example
        run: flutter build macos

      - name: Build Android
        working-directory: ./packages/posthog_flutter/example
        run: flutter build apk

      - name: Build Web
        working-directory: ./packages/posthog_flutter/example
        run: flutter build web
