name: SDK Compliance Tests

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compliance:
    name: PostHog SDK compliance tests
    uses: PostHog/posthog-sdk-test-harness/.github/workflows/test-sdk-action.yml@68498bcf3ae95ac941476e6ca3d42d6086e1c7fd
    with:
      adapter-dockerfile: "sdk_compliance_adapter/Dockerfile"
      adapter-context: "."
      test-harness-version: "0.9.0"
